spring.application.name=cinescore

# Banco de dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/cinescore
spring.datasource.username=root
spring.datasource.password=123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false

# JWT
jwt.secret=cinescore-chave-secreta-jwt-2026-producao
jwt.expiration=86400000

# TMDB API
tmdb.api.key=6fce4d756b5419a6a28a6e31dd51c085
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.image-url=https://image.tmdb.org/t/p/w500

# Hugging Face Moderation
huggingface.api.key=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
huggingface.api.url=https://api-inference.huggingface.co/models/ruanchaves/bert-base-portuguese-cased-hatebr
